
package org.apache.headers;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-08-01T14:34:53.820+05:30
 * Generated source version: 3.3.2
 *
 */

public class HeaderTester_SoapPort_Server{

    protected HeaderTester_SoapPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new SoapPortImpl();
        String address = "http://localhost:9090/CXF-Header-Service/services/SoapPort";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new HeaderTester_SoapPort_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
