package com.bank.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-07-30T17:11:05.593+05:30
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://server.bank.com", name = "Account")
@XmlSeeAlso({ObjectFactory.class})
public interface Account {

    @WebMethod
    @RequestWrapper(localName = "getAccountName", targetNamespace = "http://server.bank.com", className = "com.bank.server.GetAccountName")
    @ResponseWrapper(localName = "getAccountNameResponse", targetNamespace = "http://server.bank.com", className = "com.bank.server.GetAccountNameResponse")
    @WebResult(name = "getAccountNameReturn", targetNamespace = "http://server.bank.com")
    public java.lang.String getAccountName(

        @WebParam(name = "acNo", targetNamespace = "http://server.bank.com")
        int acNo
    );

    @WebMethod
    @RequestWrapper(localName = "readAccountBalance", targetNamespace = "http://server.bank.com", className = "com.bank.server.ReadAccountBalance")
    @ResponseWrapper(localName = "readAccountBalanceResponse", targetNamespace = "http://server.bank.com", className = "com.bank.server.ReadAccountBalanceResponse")
    @WebResult(name = "readAccountBalanceReturn", targetNamespace = "http://server.bank.com")
    public int readAccountBalance(

        @WebParam(name = "name", targetNamespace = "http://server.bank.com")
        java.lang.String name
    );
}
