
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.bank.server;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-07-30T17:11:05.433+05:30
 * Generated source version: 3.3.2
 *
 */

@javax.jws.WebService(
                      serviceName = "AccountService",
                      portName = "Account",
                      targetNamespace = "http://server.bank.com",
                      wsdlLocation = "file:/D:/Java-services/WSDL-Service/WebContent/AccountService.wsdl",
                      endpointInterface = "com.bank.server.Account")

public class AccountImpl implements Account {

    private static final Logger LOG = Logger.getLogger(AccountImpl.class.getName());

    /* (non-Javadoc)
     * @see com.bank.server.Account#getAccountName(int acNo)*
     */
    public java.lang.String getAccountName(int acNo) {
        LOG.info("Executing operation getAccountName");
        System.out.println(acNo);
        try {
            java.lang.String _return = "account with "+acNo;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.bank.server.Account#readAccountBalance(java.lang.String name)*
     */
    public int readAccountBalance(java.lang.String name) {
        LOG.info("Executing operation readAccountBalance");
        System.out.println(name);
        try {
            int _return = name.length() * 100;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
