package com.bank.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-07-30T17:11:05.620+05:30
 * Generated source version: 3.3.2
 *
 */
@WebServiceClient(name = "AccountService",
                  wsdlLocation = "file:/D:/Java-services/WSDL-Service/WebContent/AccountService.wsdl",
                  targetNamespace = "http://server.bank.com")
public class AccountService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://server.bank.com", "AccountService");
    public final static QName Account = new QName("http://server.bank.com", "Account");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Java-services/WSDL-Service/WebContent/AccountService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AccountService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/Java-services/WSDL-Service/WebContent/AccountService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AccountService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AccountService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccountService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public AccountService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AccountService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AccountService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Account
     */
    @WebEndpoint(name = "Account")
    public Account getAccount() {
        return super.getPort(Account, Account.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Account
     */
    @WebEndpoint(name = "Account")
    public Account getAccount(WebServiceFeature... features) {
        return super.getPort(Account, Account.class, features);
    }

}
