package com.org.sum;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.8
 * 2013-06-22T03:35:46.902+05:30
 * Generated source version: 2.6.8
 * 
 */
@WebService(targetNamespace = "http://sum.org.com/", name = "AddNumbers")
@XmlSeeAlso({ObjectFactory.class})
public interface AddNumbers {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSum", targetNamespace = "http://sum.org.com/", className = "com.org.sum.GetSum")
    @WebMethod
    @ResponseWrapper(localName = "getSumResponse", targetNamespace = "http://sum.org.com/", className = "com.org.sum.GetSumResponse")
    public int getSum(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
}
