
package com.org.sum;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.8
 * 2013-06-22T03:35:46.824+05:30
 * Generated source version: 2.6.8
 * 
 */
public final class AddNumbers_AddNumbersClassPort_Client {

    private static final QName SERVICE_NAME = new QName("http://sum.org.com/", "AddNumbersClassService");

    private AddNumbers_AddNumbersClassPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AddNumbersClassService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AddNumbersClassService ss = new AddNumbersClassService(wsdlURL, SERVICE_NAME);
        AddNumbers port = ss.getAddNumbersClassPort();  
        
        {
        System.out.println("Invoking getSum...");
        int _getSum_arg0 = -1369825284;
        int _getSum_arg1 = -2008080917;
        int _getSum__return = port.getSum(_getSum_arg0, _getSum_arg1);
        System.out.println("getSum.result=" + _getSum__return);


        }

        System.exit(0);
    }

}
