
package com.server;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.8
 * 2013-06-21T01:04:43.440+05:30
 * Generated source version: 2.6.8
 * 
 */
public final class EmployeeInfo_EmployeeInfoPort_Client {

    private static final QName SERVICE_NAME = new QName("http://server.com/", "EmployeeInfoService");

    private EmployeeInfo_EmployeeInfoPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = EmployeeInfoService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        EmployeeInfoService ss = new EmployeeInfoService(wsdlURL, SERVICE_NAME);
        EmployeeInfo port = ss.getEmployeeInfoPort();  
        
        {
        System.out.println("Invoking getEmployees...");
        java.util.List<com.server.Employee> _getEmployees__return = port.getEmployees();
        System.out.println("getEmployees.result=" + _getEmployees__return);


        }
        {
        System.out.println("Invoking getEmployee...");
        java.lang.String _getEmployee_arg0 = "_getEmployee_arg0-762065866";
        com.server.Employee _getEmployee__return = port.getEmployee("Ashoka");
      //  com.server.Employee _getEmployee__return = port.getEmployee("AshokaRaj");
        
        System.out.println("getEmployee.result=" + _getEmployee__return);


        }
        {
        System.out.println("Invoking addEmployee...");
        com.server.Employee _addEmployee_arg0 = new com.server.Employee();
        _addEmployee_arg0.setEmployeeID("EmployeeID476365366");
        _addEmployee_arg0.setEmployeeName("EmployeeName1359953580");
        port.addEmployee(_addEmployee_arg0);


        }

        System.exit(0);
    }

}
