package com.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.8
 * 2013-06-21T01:04:43.518+05:30
 * Generated source version: 2.6.8
 * 
 */
@WebServiceClient(name = "EmployeeInfoService", 
                  wsdlLocation = "http://localhost:8080/CXF_SoapFaults/services/EmployeeInfoPort?wsdl",
                  targetNamespace = "http://server.com/") 
public class EmployeeInfoService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://server.com/", "EmployeeInfoService");
    public final static QName EmployeeInfoPort = new QName("http://server.com/", "EmployeeInfoPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/CXF_SoapFaults/services/EmployeeInfoPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EmployeeInfoService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/CXF_SoapFaults/services/EmployeeInfoPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EmployeeInfoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EmployeeInfoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeeInfoService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns EmployeeInfo
     */
    @WebEndpoint(name = "EmployeeInfoPort")
    public EmployeeInfo getEmployeeInfoPort() {
        return super.getPort(EmployeeInfoPort, EmployeeInfo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployeeInfo
     */
    @WebEndpoint(name = "EmployeeInfoPort")
    public EmployeeInfo getEmployeeInfoPort(WebServiceFeature... features) {
        return super.getPort(EmployeeInfoPort, EmployeeInfo.class, features);
    }

}
