<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="MyBaseService" targetNamespace="http://server.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://server.com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
<import namespace="http://server.com/" schemaLocation="mybase_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="getAccountBalance">
    <wsdl:part name="parameters" element="tns:getAccountBalance">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getAccountBalanceResponse">
    <wsdl:part name="parameters" element="tns:getAccountBalanceResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="MyClass">
    <wsdl:operation name="getAccountBalance">
      <wsdl:input name="getAccountBalance" message="tns:getAccountBalance">
    </wsdl:input>
      <wsdl:output name="getAccountBalanceResponse" message="tns:getAccountBalanceResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="MyBaseServiceSoapBinding" type="tns:MyClass">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getAccountBalance">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="getAccountBalance">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getAccountBalanceResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:portType name="MyPort">
    <wsdl:operation name="getAccountBalance">
      <wsdl:input name="getAccountBalance" message="tns:getAccountBalance">
    </wsdl:input>
      <wsdl:output name="getAccountBalanceResponse" message="tns:getAccountBalanceResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="MyServiceSoapBinding" type="tns:MyPort">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getAccountBalance">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="getAccountBalance">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getAccountBalanceResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="MyService">
    <wsdl:port name="MyClass" binding="tns:MyBaseServiceSoapBinding">
      <soap:address location="http://localhost:8080/Service/services/MyServicePort"/>
    </wsdl:port>
    <wsdl:port name="MyPort" binding="tns:MyServiceSoapBinding">
      <soap:address location="http://localhost:8080/Service/services/MyPort"/>
    </wsdl:port>
  </wsdl:service>
  
  <wsdl:service name="TestService">
    <wsdl:port name="MyClass" binding="tns:MyBaseServiceSoapBinding">
      <soap:address location="http://localhost:8080/Service/services/TestPort1"/>
    </wsdl:port>
    <wsdl:port name="MyPort" binding="tns:MyServiceSoapBinding">
      <soap:address location="http://localhost:8080/Service/services/TestPort2"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
