
package com.server.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.8
 * Fri Jun 21 01:01:11 IST 2013
 * Generated source version: 2.6.8
 */

@XmlRootElement(name = "NoSuchEmployeeFault", namespace = "http://server.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NoSuchEmployeeFault", namespace = "http://server.com/", propOrder = {"info", "message"})

public class NoSuchEmployeeFaultBean {

    private java.lang.String info;
    private java.lang.String message;

    public java.lang.String getInfo() {
        return this.info;
    }

    public void setInfo(java.lang.String newInfo)  {
        this.info = newInfo;
    }

    public java.lang.String getMessage() {
        return this.message;
    }

    public void setMessage(java.lang.String newMessage)  {
        this.message = newMessage;
    }

}

