package org.data;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-07-30T16:06:18.053+05:30
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://data.org/", name = "Human")
//@XmlSeeAlso({ObjectFactory.class})
public interface Human {

    @WebMethod
    @RequestWrapper(localName = "calculateSalary", targetNamespace = "http://data.org/", className = "org.data.CalculateSalary")
    @ResponseWrapper(localName = "calculateSalaryResponse", targetNamespace = "http://data.org/", className = "org.data.CalculateSalaryResponse")
    @WebResult(name = "return", targetNamespace = "")
    public double calculateSalary(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getNameofEmployee", targetNamespace = "http://data.org/", className = "org.data.GetNameofEmployee")
    @ResponseWrapper(localName = "getNameofEmployeeResponse", targetNamespace = "http://data.org/", className = "org.data.GetNameofEmployeeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getNameofEmployee(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
