
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.apache.cxf;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import javax.activation.DataHandler;

/**
 * This class was generated by Apache CXF 2.6.8
 * 2013-06-22T02:21:28.399+05:30
 * Generated source version: 2.6.8
 * 
 */

@javax.jws.WebService(
                      serviceName = "MtomService",
                      portName = "MtomPort",
                      targetNamespace = "http://cxf.apache.org/",
                      wsdlLocation = "http://localhost:8080/Cxf_MTOM_Attachments/services/MtomPort?wsdl",
                      endpointInterface = "org.apache.cxf.MTomPort")
                      
public class MTomPortImpl implements MTomPort {

    private static final Logger LOG = Logger.getLogger(MTomPortImpl.class.getName());

    /* (non-Javadoc)
     * @see org.apache.cxf.MTomPort#attachByteArray(java.lang.String  arg0 ,)byte[]  arg1 )*
     */
    public void attachByteArray(javax.xml.ws.Holder<java.lang.String> arg0,javax.xml.ws.Holder<byte[]> arg1) { 
        LOG.info("Executing operation attachByteArray");
        System.out.println(arg0.value);
        System.out.println(arg1.value);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.apache.cxf.MTomPort#attachDataHandler(java.lang.String  arg0 ,)byte[]  arg1 )*
     */
    public void attachDataHandler(javax.xml.ws.Holder<java.lang.String> arg0,javax.xml.ws.Holder<DataHandler> arg1) { 
        LOG.info("Executing operation attachDataHandler");
        System.out.println(arg0.value);
        System.out.println(arg1.value);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
