package org.apache.cxf;

import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.8
 * 2013-06-22T02:21:28.414+05:30
 * Generated source version: 2.6.8
 * 
 */
@WebService(targetNamespace = "http://cxf.apache.org/", name = "MTomPort")
@XmlSeeAlso({ObjectFactory.class})
public interface MTomPort {

    @RequestWrapper(localName = "attachByteArray", targetNamespace = "http://cxf.apache.org/", className = "org.apache.cxf.AttachByteArray")
    @WebMethod
    @ResponseWrapper(localName = "attachByteArrayResponse", targetNamespace = "http://cxf.apache.org/", className = "org.apache.cxf.AttachByteArrayResponse")
    public void attachByteArray(
        @WebParam(mode = WebParam.Mode.INOUT, name = "arg0", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> arg0,
        @WebParam(mode = WebParam.Mode.INOUT, name = "arg1", targetNamespace = "")
        javax.xml.ws.Holder<byte[]> arg1
    );

    @RequestWrapper(localName = "attachDataHandler", targetNamespace = "http://cxf.apache.org/", className = "org.apache.cxf.AttachDataHandler")
    @WebMethod
    @ResponseWrapper(localName = "attachDataHandlerResponse", targetNamespace = "http://cxf.apache.org/", className = "org.apache.cxf.AttachDataHandlerResponse")
    public void attachDataHandler(
        @WebParam(mode = WebParam.Mode.INOUT, name = "arg0", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> arg0,
        @WebParam(mode = WebParam.Mode.INOUT, name = "arg1", targetNamespace = "")
        javax.xml.ws.Holder<DataHandler> arg1
    );
}
