
package com.org.sum.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.8
 * Sat Jun 22 03:34:25 IST 2013
 * Generated source version: 2.6.8
 */

@XmlRootElement(name = "getSumResponse", namespace = "http://sum.org.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getSumResponse", namespace = "http://sum.org.com/")

public class GetSumResponse {

    @XmlElement(name = "return")
    private int _return;

    public int getReturn() {
        return this._return;
    }

    public void setReturn(int new_return)  {
        this._return = new_return;
    }

}

